MONGO_DB_HOST: mongodb-{{ envir }}.believeinyou.fun
REDIS_HOST: redis-{{ envir }}.believeinyou.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ envir }}.believeinyou.fun
CART_HOST: cart.backend-alb-{{ envir }}.believeinyou.fun
MYSQL_HOST: mysql-{{ envir }}.believeinyou.fun
USER_HOST: user.backend-alb-{{ envir }}.believeinyou.fun
RABBITMQ_HOST: rabbitmq-{{ envir }}.believeinyou.fun
SHIPPING_HOST: shipping.backend-alb-{{ envir }}.believeinyou.fun
PAYMENT_HOST: payment.backend-alb-{{ envir }}.believeinyou.fun