MONGO_DB_HOST: mongodb-{{ envir }}..believeinyou.fun
REDIS_HOST: redis-{{ envir }}..believeinyou.fun
CATALOGUE_HOST: catalogue-{{ envir }}..believeinyou.fun
CART_HOST: cart-{{ envir }}..believeinyou.fun
MYSQL_HOST: mysql-{{ envir }}..believeinyou.fun
USER_HOST: user-{{ envir }}..believeinyou.fun
RABBITMQ_HOST: rabbitmq-{{ envir }}..believeinyou.fun
SHIPPING_HOST: shipping-{{ envir }}..believeinyou.fun
PAYMENT_HOST: payment-{{ envir }}..believeinyou.fun